#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "$HIVE_USER" WITH PASSWORD '$HIVE_PASSWORD';
  CREATE DATABASE "$HIVE_DB";
  GRANT ALL PRIVILEGES ON DATABASE "$HIVE_DB" TO "$HIVE_USER";

  CREATE USER "$SANDBOX_USER" WITH PASSWORD '$SANDBOX_PASSWORD';
  CREATE DATABASE "$SANDBOX_DB";
  GRANT ALL PRIVILEGES ON DATABASE "$SANDBOX_DB" TO "$SANDBOX_USER";
EOSQL
